JNG-4269_SemiAutomaticSchemaUpgrade
BlackBeltTechnology/judo-meta-asm pull request #80
Opened 2023-02-23 07:11 UTC by robertcsakany

JNG-4269_SemiAutomaticSchemaUpgrade

2023-02-26 17:44 UTC, noherczeg requested changes

2023-02-26 17:44 UTC, noherczeg commented on osgi/src/main/java/hu/blackbelt/judo/meta/asm/osgi/AsmModelBundleTracker.java
> +                        log.error("Could not load Psm model: " + params.get(AsmModel.NAME) + " from bundle: " + trackedBundle.getBundleId(), e);
PSM?

2023-02-27 10:12 UTC, noherczeg approved these changes

2023-02-27 15:39 UTC, fmagnucz approved these changes

2023-02-27 16:42 UTC, merged