JNG-4490  Release judo meta asm
BlackBeltTechnology/judo-meta-asm pull request #82
Opened 2023-02-27 15:30 UTC by gaborflorian

2023-02-27 15:32 UTC, noherczeg approved these changes

2023-02-27 17:04 UTC, fmagnucz approved these changes

2023-02-28 11:02 UTC, robertcsakany approved these changes

2023-02-28 21:55 UTC, bencegelei requested changes

2023-02-28 21:55 UTC, bencegelei commented on pom.xml
> +				<version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:34 UTC, gaborflorian commented on pom.xml
> +				<version>1.2.11</version>
Requested by Robert

2023-03-01 09:41 UTC, robertcsakany approved these changes

2023-03-01 11:59 UTC, bencegelei approved these changes

2023-03-09 10:16 UTC, merged